name: Build Node.js app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build --if-present

#      - name: npm test
#        run: npm run test --if-present