name: Build Node.js app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-pack:
    name: Build and pack
    uses: ./.github/workflows/build-pack.yml
    with:
      APPLICATION_NAME: group-by.web.app
      ONLY_BUILD: true
