name: Build Node.js app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-pack:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Build and pack application
      uses: ./.github/workflows/build-pack.yml
      with:
        ONLY_BUILD: true