name: Create release

on:
  push:
    tags:
      - 'v*'
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  APPLICATION_NAME: group-by.web.app

jobs:
  build-pack:
    runs-on: ubuntu-latest

    steps:
    - name: Build and pack application
      uses: ./.github/workflows/build-pack.yml
      with:
        APPLICATION_NAME: ${{ env.APPLICATION_NAME }}
        ONLY_BUILD: false

  build-release:
    name: Build docker image
    uses: ./.github/workflows/build-docker-image.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      DEV_RELEASE: false
    secrets: inherit
    needs: build-pack
    permissions:
      contents: read
      packages: write

  release-project:
    name: Create release
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Genereate changelog
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: CHANGELOG.md
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.APPLICATION_NAME }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ${{ env.APPLICATION_NAME }}.tar.gz
            CHANGELOG.md